"use client";

import { useRef } from "react";
import { createPortal } from "react-dom";
import { Close, Download, ArrowUpRight } from "./Icons";
import { asset, site } from "@/lib/site";
import { useDialog } from "@/lib/useDialog";

const RESUME_PATH = "/assets/Kyle_Gregory_Ibo_Resume.pdf";
const FILE_NAME = "Kyle_Gregory_Ibo_Resume.pdf";

/**
 * A rendered picture of the PDF's one page, regenerated by
 * `npm run resume:preview` whenever the PDF changes. The dialog shows this
 * rather than embedding the PDF: an <object> embed only works where the
 * browser has a PDF viewer, which phones and some desktop setups don't, and
 * there the visitor got an empty panel and an apology. The PDF itself stays
 * one click away for download and text selection.
 */
const PREVIEW_PATH = "/assets/resume-preview.webp";
const PREVIEW_WIDTH = 1600;
const PREVIEW_HEIGHT = 2071;

export function ResumeModal({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) {
  const panelRef = useRef<HTMLDivElement>(null);

  // Escape, scroll lock, focus park/restore and the Tab trap — see useDialog.
  useDialog({ open, onClose, panelRef });

  if (!open) return null;

  const href = asset(RESUME_PATH);

  const modal = (
    <div
      className="animate-overlay-in fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-3 backdrop-blur-sm sm:p-6"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="resume-modal-title"
        tabIndex={-1}
        className="animate-panel-in flex max-h-[92dvh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl border border-border bg-bg shadow-2xl outline-none"
      >
        <div className="flex items-center justify-between gap-3 border-b border-border px-4 py-3.5 sm:px-6 sm:py-4">
          <div className="min-w-0">
            <h2
              id="resume-modal-title"
              className="text-base font-semibold sm:text-lg"
            >
              Résumé
            </h2>
            <p className="truncate text-xs text-muted sm:text-sm">
              <span className="sm:hidden">One page · PDF</span>
              <span className="hidden sm:inline">
                {site.name} — {site.role}
              </span>
            </p>
          </div>

          <div className="flex shrink-0 items-center gap-2">
            <a
              href={href}
              target="_blank"
              rel="noreferrer"
              aria-label="Open the PDF in a new tab"
              className="inline-flex h-9 items-center justify-center gap-2 rounded-full border border-border px-2.5 text-sm font-medium text-muted transition-colors hover:border-fg hover:text-fg sm:px-4"
            >
              <ArrowUpRight className="h-4 w-4" />
              <span className="hidden sm:inline">Open</span>
            </a>
            <a
              href={href}
              download={FILE_NAME}
              className="inline-flex h-9 items-center gap-2 rounded-full bg-accent px-3.5 text-sm font-medium text-accent-fg transition-opacity hover:opacity-90 sm:px-4"
            >
              <Download className="h-4 w-4" />
              Download
              <span className="sr-only"> the résumé as a PDF</span>
            </a>
            <button
              type="button"
              onClick={onClose}
              aria-label="Close résumé"
              className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-border text-muted transition-colors hover:border-fg hover:text-fg"
            >
              <Close className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* The page sits on the surface like a sheet on a desk, and scrolls
            inside the dialog so the actions above never leave the screen. */}
        <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain bg-surface px-3 py-4 sm:px-10 sm:py-8">
          <a
            href={href}
            target="_blank"
            rel="noreferrer"
            className="group mx-auto block max-w-[680px] rounded-[4px] bg-white shadow-[0_1px_2px_rgba(16,14,12,0.08),0_18px_40px_-20px_rgba(16,14,12,0.35)] transition-shadow hover:shadow-[0_1px_2px_rgba(16,14,12,0.08),0_24px_48px_-18px_rgba(16,14,12,0.45)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={asset(PREVIEW_PATH)}
              width={PREVIEW_WIDTH}
              height={PREVIEW_HEIGHT}
              decoding="async"
              alt={`${site.name}'s résumé. Open the PDF for selectable text.`}
              className="block h-auto w-full rounded-[4px]"
            />
          </a>
          {/* At phone width the page is legible only as a layout; say how to read it. */}
          <p className="mt-3 text-center text-xs text-muted sm:hidden">
            Tap the page to open it full size.
          </p>
        </div>
      </div>
    </div>
  );

  return createPortal(modal, document.body);
}
